name: E-commerce CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 7.0.x # Projede kullandığınız .NET Core sürümünü buraya ekleyin

    - name: Restore dependencies
      run: dotnet restore

    - name: Build the project
      run: dotnet build --no-restore --configuration Release

    - name: Run tests
      run: dotnet test --no-build --verbosity normal

    - name: Publish build artifacts (optional)
      if: success()
      run: dotnet publish -c Release -o ./publish

    - name: Upload build artifacts (optional)
      uses: actions/upload-artifact@v2
      with:
        name: e-commerce-build
        path: ./publish

